name: Build MacOS
on: [push]
jobs:
  build:
    name: Build MacOS
    runs-on: macos-13
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v1.14.1
        with:
          cmake-version: '3.27.x'

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.20'

      - name: deps fetch dependencies
        run:
          go run github.com/piot/deps/src/deps@main fetch -m clone -t src/deps --dev

      - name: create cmake cache
        run: cmake -DCMAKE_BUILD_TYPE=Debug .
        working-directory: src/

      - name: build
        run: cmake --build . --clean-first
        working-directory: src/

      - uses: actions/upload-artifact@v2
        with:
          name: Audio Queue Service MacOS Library
          path: |
            src/lib/libaudio-queue-service.a
